server:
  port: 8081
  tomcat:
    basedir: ./
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 60m

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: inspector
  freemarker:
    suffix: .ftl
    cache: false
  datasource:
    url: jdbc:mysql://118.67.131.35:3306/inspector?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: inspector
    password: "NewPass1@!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
