server:
  port: 8081
  tomcat:
    basedir: ./
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 60m

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: inspector
  freemarker:
    suffix: .ftl
    cache: false
  datasource:
    url: jdbc:mariadb://localhost:3306/finalproject?useUnicode=true&characterEncoding=utf8 # serverip:port/dbname
    username: root               # Replace with your database username
    password: "newPassword1234"                          # Database password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
# ... (any other configurations)
